---
ErrorTestSuites:
  Data mining:
    - HSVFromRGBTest
  Input/Output:
    - LASInoutTest
  Utils:
    - PredictionReducerTest
    - FPSDecoratorTest
  Deep learning:
    - ReceptiveFieldTest
    - FPSPreProcessingTest
    - HierarchicalReceptiveFieldTest
    - FeaturesDownsamplingLayerTest
    - FeaturesUpsamplingLayerTest
    - GroupingPointNetLayerTest
    - KPConvLayerTest
    - StridedKPConvLayerTest
    - LightKPConvLayerTest
    - StridedLightKPConvLayerTest
    - HourglassLayerTest
    - SubmanifoldSpConv3DLayerTest
    - DownsamplingSpConv3DLayerTest
    - UpsamplingSpConv3DLayerTest
    - ShadowDenseLayerTest
    - ShadowConv1DLayerTest
    - ShadowBatchNormalizationLayerTest
    - ShadowActivationLayerTest
    - RaggedLossesTest
    - DLSparseShadowSequencerTest
    #- SpConv3DEncodingLayerTest
  C++:
    - VL3DPPBindingTest
    - VL3DPPBackendTest
    - VL3DPPSupportNeighborhoodsTest
    - VL3DPPOversamplerTest
    - VL3DPPDLFPSPreProcTest
    - VL3DPPDLHierarchicalFPSPreProcTest
    - VL3DPPDLLabelReductionTest
    - VL3DPPDLPostProcTest
    - VL3DPPHierarchicalSparseGridTest
    - VL3DPPDLHierarchicalSGPreProcTest
    - VL3DPPDLHierarchicalSGPostProcTest

WarningTestSuites:
  Deep learning:
    - KerasTest
    - RBFFeatExtractLayerTest
    - RBFFeatProcessingLayerTest
    - FeaturesStructuringLayerTest
    - ModelSerializationTest
...
