#ifndef VL3DPP_FURTHEST_POINT_SUBSAMPLER_
#define VL3DPP_FURTHEST_POINT_SUBSAMPLER_

// ***   INCLUDES   *** //
// ******************** //
#include <util/VL3DPPCustomOpenMP.hpp>
#include <util/VL3DPPException.hpp>
#include <util/VL3DPPMacros.hpp>
#include <util/MultithreadingUtils.hpp>

#include <armadillo>

#include <sstream>

using vl3dpp::util::VL3DPP_OMP_Opt;
using vl3dpp::util::VL3DPPException;


namespace vl3dpp::alg{
/**
 * @author Alberto M. Esmoris Pena
 * @brief Class providing different logics to compute (both exactly and
 *  approximately) the furthest point sampling of a point cloud.
 *
 * Let \f$X = \left\{\pmb{x}_1, \ldots, \pmb{x}_m\right\}\f$ be a set of
 * \f$m\f$ points. The FPS with size \f$R\f$ (target number of points)
 * algorithm will yield another set \f$Y \subseteq X\f$ with
 * \f$R\f$ points from \f$X\f$. At a given \f$t\f$ iteration, the index
 * \f$k_t\f$ of the selected point will be obtained by solving:
 *
 * \f[
 *  k_t = \text{argmax}_{1 \leq k \leq m, \pmb{x}_k \notin Y_{t-1}} \quad
 *      \min_{\pmb{y} \in Y_t} \quad {||}{
 *          \pmb{y} - \pmb{x}_k
 *      }{||}^2
 * \f]
 *
 * Where \f$Y_{t-1}\f$ is the set of selected points at the \f$t-1\f$
 * iteration.
 *
 * @tparam XDecimalType The type of decimal number.
 */
template <typename XDecimalType>
class FurthestPointSubsampler {
protected:
    // ***  ATTRIBUTES : SPECIFICATION  *** //
    // ************************************ //
    /**
     * @brief The number of points that must be generated by furthest point
     *  subsampling.
     */
    arma::uword targetPoints;
    /**
     * @brief How many threads must be used.
     *
     * If 0, then the number of threads depends on the current configuration.
     * If -1, then all available threads will be used.
     */
    int const nthreads;

public:
    // ***  CONSTRUCTION / DESTRUCTION  *** //
    // ************************************ //
    /**
     * @brief Instantiate a FurthestPointSubsampler algorithm.
     * @see FurthestPointSubsampler::targetPoints
     */
    FurthestPointSubsampler(
        arma::uword const targetPoints,
        int const nthreads
    );
    virtual ~FurthestPointSubsampler() = default;

    // ***   EXHAUSTIVE FPS METHODS   *** //
    // ********************************** //
    /**
     * @brief Transform the given input structure space to its FPS
     *  representation.
     * @param X The input structure space.
     * @return The FPS representation of the input structure space.
     */
    arma::Mat<XDecimalType> sample(arma::Mat<XDecimalType> const &X) const;
    /**
     * @brief Version of FurthestPointSubsampler::sample specifically optimized
     *  for 2D points.
     */
    arma::Mat<XDecimalType> sample2D(arma::Mat<XDecimalType> const &X) const;
    /**
     * @brief Version of FurthestPointSubsampler::sample specifically optimized
     *  for 3D points.
     */
    arma::Mat<XDecimalType> sample3D(arma::Mat<XDecimalType> const &X) const;

    // ***  PARALLEL STOCHASTIC FPS METHODS  *** //
    // ***************************************** //
    /**
     * @brief Like FurthestPointSubsampler::sample but in parallel. Note that
     *  the parallelization is not deterministic.
     * @see FurthestPointSubsampler::sample
     */
    arma::Mat<XDecimalType> parallelSample(
        arma::Mat<XDecimalType> const &X
    ) const;
    /**
     * @brief Version of FurthestPointSubsampler::parallelSample specifically
     *  optimized for 2D points.
     */
    arma::Mat<XDecimalType> parallelSample2D(
        arma::Mat<XDecimalType> const &X
    ) const;
    /**
     * @brief Version of FurthestPointSubsampler::parallelSample specifically
     *  optimized for 3D points.
     */
    arma::Mat<XDecimalType> parallelSample3D(
        arma::Mat<XDecimalType> const &X
    ) const;

    // ***  HYBRID STOCHASTIC FPS METHODS  *** //
    // *************************************** //
    /**
     * @brief Like FurthestPointSubsampler::sample but using a two steps
     *  procedure.
     *
     * In the first step, a uniform downsampling is applied to the points.
     * In the second step, if the uniform downsampling step did not divide the
     *  target number of points, an exact FPS on the downsampled representation
     *  is used to complete the FPS.
     *
     * @see FurthestPointSubsampler::sample
     */
    arma::Mat<XDecimalType> hybridSample(
        arma::Mat<XDecimalType> const &X
    ) const;
    /**
     * @brief Version of FurthestPointSubsampler::hybridSample specifically
     *  optimized for 2D points.
     */
    arma::Mat<XDecimalType> hybridSample2D(
        arma::Mat<XDecimalType> const &X
    ) const;
    /**
     * @brief Version of FurthestPointSubsampler::hybridSample specifically
     *  optimized for 3D points.
     */
    arma::Mat<XDecimalType> hybridSample3D(
        arma::Mat<XDecimalType> const &X
    ) const;
protected:
    /**
     * @brief Assist the FurthestPointSubsampler::hybridSample method (and its
     *  2D and 3D versions) to do a down sample that will potentially take more
     *  points than target points. If this is the case, then an exact FPS will
     *  be computed on it. For a end-to-end down sample method see
     *  FurthestPointSubsampler::downSample .
     * @see FurthestPointSubsampler::hybridSample
     * @see FurthestPointSubsampler::hybridSampled2D
     * @see FurthestPointSubsampler::hybridSample3D
     * @see FurthestPointSubsampler::downSample
     */
    arma::Mat<XDecimalType> overDownSample(
        arma::Mat<XDecimalType> const &X
    ) const;


public:
    // ***  FULL STOCHASTIC FPS METHODS  *** //
    // ************************************* //
    /**
     * @brief Like FurthestPointSubsampler::hybridSample but no exact FPS is
     *  used, instead, the downsampling stops when the target number of points
     *  has been reached. Note that this might lead to problems when point
     *  clouds are sorted in particular ways, e.g., by acquisition time, as the
     *  missing points will be concentrated on the final indices.
     *
     * @see FurthestPointSubsampler::sample
     */
    arma::Mat<XDecimalType> downSample(
        arma::Mat<XDecimalType> const &X
    ) const;
    /**
     * @brief Like FurthestPointSubsampler::sample but selecting the FPS points
     *  by random sampling without repetitions.
     *
     * @see FurthestPointSubsampler::sample
     */
    arma::Mat<XDecimalType> randomSample(
        arma::Mat<XDecimalType> const &X
    ) const;
    /**
     * @brief Version of FurthestPointSubsampler::randomSample specifically
     *  optimized for 2D points.
     */
    arma::Mat<XDecimalType> randomSample2D(
        arma::Mat<XDecimalType> const &X
    ) const;
    /**
     * @brief Version of FurthestPointSubsampler::randomSample specifically
     *  optimized for 3D points.
     */
    arma::Mat<XDecimalType> randomSample3D(
        arma::Mat<XDecimalType> const &X
    ) const;


};


#include <alg/FurthestPointSubsampler.tpp>


}

#endif
