#ifndef VL3DPP_HIERARCHICAL_SPARSE_GRID_
#define VL3DPP_HIERARCHICAL_SPARSE_GRID_

// ***   INCLUDES   *** //
// ******************** //
#include <util/VL3DPPException.hpp>
#include <util/VL3DPPMacros.hpp>
#include <util/TimeWatcher.hpp>
#include <util/logging/GlobalLogger.hpp>
#include <adt/grid/SparseGrid.hpp>

#include <armadillo>

#include <map>


namespace vl3dpp::adt::grid{

using vl3dpp::util::TimeWatcher;
using std::map;
using std::string;
using std::vector;

/**
 * @author Alberto M. Esmoris Pena
 * @version 1.0
 *
 * @brief Hierarchical sparse grid.
 *
 * The hierarchical sparse grid of max depth \f$t^* \in \mathbb{Z}_{>0}\f$
 * builds an adt::grid::SparseGrid and then as many sparse grids as needed until
 * a hierarchy of \f$t^*\f$ sparse grids. The subsequent sparse grids are built
 * considering a given window and stride (step size) that moves along the
 * previous sparse grid. Thus, the number of cells in the sparse grids after
 * the first one depend on the window size and stride specification.
 *
 * Note that in a hierarchical sparse grid the first sparse grid needs two
 *  indices per active cell, one to link the cell index (sparse) with the
 *  active cell index (sequential) (see HierarchicalSparseGrid::h) and one to
 *  link the active cell index with the min active cell in the second sparse
 *  grid (see HierarchicalSparseGrid::hU). The last sparse grid needs two
 *  indices per active cell, one to link
 *  the cell index (sparse) with the active cell index (sequential) (see
 *  HierarchicalSparseGrid::h) and one to link the active cell index with the
 *  min active cell in the sparse grid before the last one (see
 *  HierarchicalSparseGrid::hD). All the intermediate sparse grid need three
 *  indices per active cell, to link the cell index (sparse) with the active
 *  cell index (sequential) (see HierarchicalSparseGrid::h), one to link the
 *  active cell index with the min active cell index in the previous grid
 *  (see HierarchicalSparseGrid::hD), and one to link the active cell index
 *  with the min active cell index in the next grid (see
 *  HierarchicalSparseGrid::hU).
 *
 * @tparam XDecimalType The type of decimal number for the coordinates (
 *  structure space).
 * @tparam IndexType The type of integer number used for cell and point-wise
 *  indexing.
 * @see adt::grid::SparseGrid
 */
template <typename XDecimalType=float, typename IndexType=int>
class HierarchicalSparseGrid{
protected:
    // ***  ATTRIBUTES : SPECIFICATION  *** //
    // ************************************ //
    /**
     * @brief The window size at each depth for sparse submanifold convolutions.
     *
     * For a hierarchical sparse grid of max depth
     *  \f$t^* \in \mathbb{Z}_{>1}\f$, the window size for submanifold
     *  convolutions \f$w_{t}\f$ is needed to determine the axis-wise padding
     *  of the sparse grid at depth \f$t\f$. There are \f$t^*\f$ window sizes
     *  for submanifold convolutions.
     *
     * Note that, contrary to standard convolutions, submanifold convolutions
     *  are odd. Thus, a window size \f$w_t\f$ means that \f$w_t\f$ neighbors
     *  will be taken towards the negative direction and \f$w_t\f$ neighbors
     *  will be taken towards the positive direction for any dimension/axis
     *  at depth \f$t\f$.
     */
    arma::Col<IndexType> w;
    /**
     * @brief The downsampling window size at each depth.
     *
     * For a hierarchical sparse grid of max depth
     *  \f$t^* \in \mathbb{Z}_{>1}\f$,
     *  the downsampling window size \f$w_{t}^D\f$ means that the cells of the
     *  sparse grid at depth \f$t+1\f$ are generated by moving a window with
     *  \f$w_t^D\f$ cells per axis/dimension through the sparse grid at depth
     *  \f$t\f$. There are \f$t^*-1\f$ downsampling window sizes.
     */
    arma::Col<IndexType> wD;
    /**
     * @brief The upsampling window size at each depth.
     *
     * For a hierarchical sparse grid of max depth
     *  \f$t^* \in \mathbb{Z}_{>1}\f$,
     *  the upsampling window size \f$w_t^U\f$ means that the cells of the
     *  sparse grid at depth \f$t\f$ are generated by moving a window with
     *  \f$w_t^U\f$
     *  cells per axis/dimension through the sparse grid at depth \f$t+1\f$.
     *  There are \f$t^*-1\f$ upsampling window sizes.
     */
    arma::Col<IndexType> wU;
    /**
     * @brief The downsampling stride (step size) at each depth.
     *
     * For a hierarchical sparse grid of max depth
     *  \f$t^* \in \mathbb{Z}_{>1}\f$, the stride
     *  \f$s_t^D\f$ means that the cells of the sparse grid at depth \f$t+1\f$
     *  are generated by moving a window with a step size of \f$s_t^D\f$ cells
     *  per axis/dimension through the sparse grid at depth \f$t\f$. There
     *  are \f$t^*-1\f$ downsampling strides.
     */
    arma::Col<IndexType> sD;
    /**
     * @brief The upsampling stride (step size) at each depth.
     *
     * For a hierarchical sparse grid of max depth
     *  \f$t^* \in \mathbb{Z}_{>1}\f$, the stride
     *  \f$s_t^U\f$ means that the cells of the sparse grid at depth \f$t\f$
     *  are generated by moving a window with a step size of \f$s_t^U\f$ cells
     *  per axis/dimension through the sparse grid at depth \f$t+1\f$. There
     *  are \f$t^*-1\f$ upsampling strides.
     */
    arma::Col<IndexType> sU;

    /**
     * @brief Whether to write/print the execution time of the fit method
     *  when building a hierarchical sparse grid (true) or not (false, default).
     */
    bool logTime;

    // ***  ATTRIBUTES : STATE  *** //
    // **************************** //
    /**
     * @brief The initial sparse grid.
     */
    SparseGrid<XDecimalType, IndexType> sg;
    /**
     * @brief Key-value map (to be used as static hash table) that maps the
     *  cell index (key) to the corresponding active cell index (value) for
     *  each sparse grid after the first one. Note that the corresponding map
     *  for the first sparse grid is inside HierarchicalSparseGrid::sg at
     *  SparseGrid::h.
     *
     * @see SparseGrid::h
     */
    vector<map<IndexType, IndexType>> h;
    /**
     * @brief Indexing tuple that maps the active cell index \f$k\f$ at depth
     *  \f$t\f$ with the corresponding cell index at depth \f$t-1\f$.
     *
     * By convention, the active cell at depth \f$t\f$ is mapped to the min
     *  cell inside the corresponding downsampling convolutional window applied
     *  to the sparse grid at depth \f$t-1\f$ (e.g., in 2D to the lower-left
     *  corner, in 3D to the lower-left-backward corner, etc.).
     *
     * The notation \f$h^D_{tk}\f$ gives the index of the min vertex in the
     *  sparse grid at depth \f$t-1\f$ that corresponds to the start of the
     *  convolutional neighborhood that defines the value for the \f$k\f$-th
     *  active cell of the sparse grid at depth \f$t\f$.
     */
    vector<vector<IndexType>> hD;
    /**
     * @brief Indexing tuple that maps the active cell index \f$k\f$ at depth
     *  \f$t\f$ with the corresponding cell index at depth \f$t+1\f$.
     *
     * By convention, the active cell at depth \f$t\f$ is mapped to the min
     *  cell inside the corresponding upsampling convolutional window applied
     *  to the sparse grid at depth \f$t+1\f$ (e.g., in 2D to the lower-left
     *  corner, in 3D to the lower-left-backward corner, etc.).
     *
     * The notation \f$h^U_{tk}\f$ gives the index of the min vertex in the
     *  sparse grid at depth \f$t+1\f$ that corresponds to the start of the
     *  convolutional neighborhood that defines the value for the \f$k\f$-th
     *  active cell of the sparse grid at depth \f$t\f$.
     */
    vector<vector<IndexType>> hU;
    /**
     * @brief The number of partitions for each depth \f$t\f$ along each axis.
     *
     * Note that \f$\pmb{n}_{dt} \in \mathbb{Z}_{\geq 0}^{n_x}\f$ gives
     *  the number of partitions along the \f$d\f$-th axis/dimension of the
     *  sparse grid at depth \f$t\f$ for each sparse grid after the first one.
     *  For the particular case of the first sparse grid, the number of
     *  partitions is inside HierarchicalSparseGrid::sg at SparseGrid::n.
     *
     * @see SparseGrid::n
     */
    arma::Mat<IndexType> n;


public:
    // ***  CONSTRUCTION / DESTRUCTION  *** //
    // ************************************ //
    /**
     * @brief Initialize a HierarchicalSparseGrid. Note that this constructs
     *  the object, but it does not generate the grid. Once a
     *  HierarchicalSparseGrid is built, it must be fit to a structure space to
     *  represent it by calling the HierarchicalSparseGrid::fit method
     * @see HierarchicalSparseGrid::wD
     * @see HierarchicalSparseGrid::wU
     * @see HierarchicalSparseGrid::sD
     * @see HierarchicalSparseGrid::sU
     * @see HierarchicalSparseGrid::fit
     * @see SparseGrid::size
     * @see SparseGrid::nthreads
     * @see SparseGrid
     */
    HierarchicalSparseGrid(
        XDecimalType const size,
        arma::Col<IndexType> const &w,
        arma::Col<IndexType> const &wD,
        arma::Col<IndexType> const &wU,
        arma::Col<IndexType> const &sD,
        arma::Col<IndexType> const &sU,
        int const nthreads
    );
    virtual ~HierarchicalSparseGrid() = default;


    // ***  MAIN METHODS  *** //
    // ********************** //
    /**
     * @brief Fit the hierarchical sparse grid to the given structure space.
     *
     * After calling HierarchicalSparseGrid::fit the
     *  HierarchicalSparseGrid::sg, HierarchicalSparseGrid::h,
     *  HierarchicalSparseGrid::hD, HierarchicalSparseGrid::hU,
     *  HierarchicalSparseGrid::n will be updated.
     *
     * @param[in] X The structure space (i.e., matrix of point-wise coordinates)
     *  that must be represented by the hierarchical sparse grid.
     * @see SparseGrid::fit
     * @see SparseGrid::h
     * @see HierarchicalSparseGrid::h
     * @see HierarchicalSparseGrid::hD
     * @see HierarchicalSparseGrid::hU
     * @see SparseGrid::n
     * @see HierarchicalSparseGrid::n
     * @see HierarchicalSparseGrid::buildFirstSparseGrid
     * @see HierarchicalSparseGrid::buildHierarchicalSparseGrid
     */
    void fit(arma::Mat<XDecimalType> const &X) VL3DPP_USED_;


    // ***  HIERARCHY BUILDING METHODS  *** //
    // ************************************ //
    /**
     * @brief Build the first sparse grid of the hierarchy.
     *
     * Build the first sparse grid with the corresponding padding (it is
     * calculated through the HierarchicalSparseGrid::computeHalfPadding
     * method). Also, force its hash map (SparseGrid::h) to have sequential
     * values.
     *
     * @param X The input structure space on top of which the first sparse grid
     *  must be built.
     * @param nx The dimensionality of the input structure space.
     * @see SparseGrid
     * @see SparseGrid::fit
     */
    void buildFirstSparseGrid(
        arma::Mat<XDecimalType> const &X,
        IndexType const nx
    );

    /**
     * @brief Build all the sparse grids after the first one (which is built
     *  through HierarchicalSparseGrid::buildFirstSparseGrid).
     *
     * Let
     * \f$h_t(j) \in [0, \prod_{d=1}^{n_x}{n_{dt}}) \subseteq \mathbb{Z}_{\geq 0}\f$
     * be the map that gives the sequential index corresponding
     * to the \f$j\f$-th cell in the sparse grid at the current depth such
     * that it satisfies the following order:
     *
     * \f[
     *  \forall a < b,\, h_t(a) < h_t(b)
     * \f]
     *
     * Where \f$n_{dt}\f$ is the number of partitions along the \f$d\f$-th axis
     * of the sparse grid at depth \f$t\f$ and the \f$j\f$-th cell at depth
     * \f$t\f$ must be active.
     *
     * Let \f$(\pmb{h^D_t})_{k} \in [0, \prod_{d=1}^{n_x}n_{d(t-1)}) \subseteq \mathbb{Z}_{\geq 0}\f$
     * be the index of the cell in the source sparse grid (i.e., the one at
     * depth \f$t-1\f$) that corresponds to the \f$k\f$-th active cell in the
     * sparse grid at depth \f$t\f$.
     *
     * Let \f$i\f$ be the index of an active cell in the source sparse grid
     * (depth \f$t-1\f$). For then, the index \f$j\f$ of the min vertex in the
     * sparse grid at depth \f$t\f$ such that the corresponding upsampling
     * convolution with size \f$w^U_t\f$ and stride \f$s^U_t\f$ generates a
     * value for the \f$i\f$-th cell in the source sparse grid can be computed
     * as:
     *
     * \f[
     *  j(i) = \sum_{d=1}^{n_x} \left(
     *      \left\lfloor\frac{
     *          j'(i)
     *      }{
     *          \prod_{l=d+1}^{n_x}\left\lfloor\frac{
     *              n_{lt} - w^U_t + s^U_t
    *           }{
    *               s^U_t
    *           }
     *          \right\rfloor
     *      }
     *      \right\rfloor \mod \left\lfloor\frac{
     *          n_{dt} - w^U_t + s^U_t
     *      }{
     *          s^U_t
     *      }
     *      \right\rfloor
     *  \right) s^U_t \prod_{l=d+1}^{n_x}{n_{lt}}
     * \f]
     *
     * Where:
     *
     * \f[
     *  j'(i) = \sum_{d=1}^{n_x} \left\lfloor
     *      \left(
     *          \left\lfloor \frac{
     *              i
     *          }{
     *              \prod_{l=d+1}^{n_x}{n_{l(t-1)}}
     *          }\right\rfloor \mod n_{d(t-1)}
     *      \right)
     *      \frac{
     *          \left\lfloor\frac{
     *              n_{dt} - w^U_t + s^U_t
     *          }{
     *              s^U_t
     *          }\right\rfloor
     *      }{
     *          n_{d(t-1)}
     *      }
     *  \right\rfloor \prod_{l=d+1}^{n_x}{\left\lfloor\frac{
     *      n_l - w^U_t + s^U_t
     *  }{
     *      s^U_t
     *  }\right\rfloor}
     * \f]
     *
     * @param depth The depth \f$t \in \mathbb{Z}_{>1}\f$. Note that the first
     *  depth \f$(t=1)\f$ is computed through
     *  HierarchicalSparseGrid::buildFirstSparseGrid.
     * @param maxDepth The max depth \f$t^*\in \mathbb{Z}_{\geq 1}\f$ of the
     *  hierarchy.
     * @param nx The dimensionality of the structure space
     *  \f$n_x \in \mathbb{Z}_{>0}\f$
     * @see HierarchicalSparseGrid::h
     * @see HierarchicalSparseGrid::hD
     * @see HierarchicalSparseGrid::hU
     * @see HierarchicalSparseGrid::n
     */
    void buildHierarchicalSparseGrid(
        IndexType const depth,
        IndexType const maxDepth,
        IndexType const nx
    );

protected:
    // ***  UTIL METHODS  *** //
    // ********************** //
    /**
     * @brief Compute the half padding \f$p_t \in \mathbb{Z}_{\geq 0}\f$ for a
     *  given depth \f$t \in \mathbb{Z}_{\geq 0}\f$ of the hierarchy.
     *
     * The final padding along a given axis will consist of adding \f$p_t\f$
     *  cells in the negative direction and \f$p_t\f$ cells in the positive
     *  direction, i.e., a total of \f$2 p_t\f$ cells.
     *
     * The downsampling padding \f$p^D_t\f$ at a given depth is given by the
     *  expression:
     *
     * \f[
     *  p^D_t = \max_{0 \leq d < n_x} \quad
     *  \left\{\begin{array}{l}
     *      (n_{dt}-w^D_t) \mod s^D_t & ,\, (n_{dt}-w^D_t) \mod s^D_t \equiv 0 \\
     *      s^D_t - (n_{dt}-w^D_t) \mod s^D_t &,\, \text{otherwise}
     *  \end{array}\right.
     * \f]
     *
     * Where \f$n_x\f$ gives the dimensionality of the structure space,
     * \f$w^D_t\f$ is the downsampling window size at depth \f$t\f$,
     * \f$s^D_t\f$ is the downsampling stride at depth \f$t\f$, and
     * n_{dt} is the number of partitions along the \f$d\f$-th axis at depth
     * \f$t\f$.
     *
     * The submanifold padding at a given depth is given by
     * \f$2w_t\f$, where \f$w_t\f$ is the submanifold window size at depth
     * \f$t\f$.
     *
     * The final half padding \f$p_t\f$ will then be computed as follows:
     *
     * \f[
     *  p_t^* = \max \; \{p^D_t, 2w_t\} \\
     *  2 p_t = \left\{\begin{array}{l}
     *      p_t^* & ,\, \mod 2 \equiv 0 \\
     *      p_t^* + 1 & ,\, \text{otherwise}
     *  \end{array}\right.
     * \f]
     *
     * @param nx Dimensionality of the structure space (\f$n_x\f$).
     * @param nt Number of partitions along each axis at depth \f$t\f$.
     * @param wt Submanifold window size at depth \f$t\f$.
     * @param wDt Downsampling window size from depth \f$t\f$ to \f$t+1\f$.
     * @param sDt Downsampling stride (step size) from depth \f$t\f$ to
     *  \f$t+1\f$.
     * @return The padding along each axis for one direction.
     */
    IndexType computeHalfPadding(
        IndexType const nx,
        arma::Col<IndexType> const &nt,
        IndexType const wt,
        IndexType const wDt,
        IndexType const sDt
    );

public:
    /**
     * @see vl3dpp::adt::grid::SparseGrid::encodeMatrix
     */
    template <typename FType>
    arma::Mat<FType> encodeMatrix(
        arma::Mat<XDecimalType> const &X,
        arma::Mat<FType> const &F,
        string const &reduceStrategy
    ){return sg.encodeMatrix(X, F, reduceStrategy);}
    /**
     * @see vl3dpp::adt::grid::SparseGrid::encodeVector
     */
    template <typename FType>
    arma::Col<FType> encodeVector(
        arma::Mat<XDecimalType> const &X,
        arma::Col<FType> const &F,
        string const &reduceStrategy
    ){return sg.encodeVector(X, F, reduceStrategy);}

    /**
     * @brief Report the first sparse grid in the hierarchy.
     * @see SparseGrid::report
     */
    inline void report(std::ostream &out)
    {sg.report(out);}

    // ***  GETTERs and SETTERs  *** //
    // ***************************** //
    /**
     * @brief Obtain the max depth of the hierarchy, i.e., the number of
     *  sparse grids.
     * @return The max depth of the hierarchy.
     */
    inline IndexType getMaxDepth() const
    {return w.n_rows;}
    /**
     * @brief Obtain the size of the submanifold window that moves over the
     *  sparse grid at depth \f$t\f$ to compute sparse submanifold convolutions.
     * @param depth The depth \f$t\f$.
     * @return The size of the window that operates on the grid at depth
     *  \f$t\f$ to compute submanifold sparse convolutions.
     * @see HierarchicalSparseGrid::w
     */
    inline IndexType getSubmanifoldWindow(arma::uword const depth) const
    {return w[depth];}
    /**
     * @brief Obtain the size of the downsampling window that moves over the
     *  sparse grid at depth \f$t\f$ to generate the sparse grid at depth
     *  \f$t+1\f$.
     * @param depth The depth \f$t\f$.
     * @return The size of the downsampling window that operates on the grid at
     *  depth \f$t\f$ to generate the grid at depth \f$t+1\f$.
     * @see HierarchicalSparseGrid::wD
     */
    inline IndexType getDownsamplingWindowSize(arma::uword const depth) const
    {return wD[depth];}
    /**
     * @see HierarchicalSparseGrid::getDownsamplingWindowSize
     */
    inline IndexType getDownsamplingWindow(arma::uword const depth) const
    {return getDownsamplingWindowSize(depth);}
    /**
     * @brief Obtain the size of the upsampling window that moves over the
     *  sparse grid at depth \f$t+1\f$ to generate the sparse grid at depth
     *  \f$t\f$.
     * @param depth The depth \f$t\f$.
     * @return The size of the upsampling window that operates on the grid at
     *  depth \f$t+1\f$ to generate the grid at depth \f$t\f$.
     * @see HierarchicalSparseGrid::wU
     */
    inline IndexType getUpsamplingWindowSize(arma::uword const depth) const
    {return wU[depth];}
    /**
     * @see HierarchicalSparseGrid::getUpsamplingWindowSize
     */
    inline IndexType getUpsamplingWindow(arma::uword const depth) const
    {return getUpsamplingWindowSize(depth);}
    /**
     * @brief Obtain the stride (step size) that governs how the downsampling
     *  window moves over the sparse grid at depth \f$t\f$ to generate the
     *  sparse grid at depth \f$t+1\f$.
     * @param depth The depth \f$t\f$.
     * @return The stride of the downsampling window that operates on the grid
     *  at depth \f$t\f$ to generate the grid at depth \f$t+1\f$.
     * @see HierarchicalSparseGrid::sD
     */
    inline IndexType getDownsamplingStride(arma::uword const depth) const
    {return sD[depth];}
    /**
     * @brief Obtain the stride (step size) that governs how the upsampling
     *  window moves over the sparse grid at depth \f$t+1\f$ to generate the
     *  sparse grid at depth \f$t\f$.
     * @param depth The depth \f$t\f$.
     * @return The stride of the upsampling window that operates on the grid
     *  at depth \f$t\f$ to generate the grid at depth \f$t+1\f$.
     * @see HierarchicalSparseGrid::sU
     */
    inline IndexType getUpsamplingStride(arma::uword const depth) const
    {return sU[depth];}
    /**
     * @brief Obtain the number of cells in the sparse grid at depth \f$t\f$.
     * @param depth The depth \f$t\f$.
     * @return The number of cells in the sparse grid at depth \f$t\f$.
     */
    inline IndexType getNumCells(arma::uword const depth) const
    {return depth==0 ? sg.getNumCells() : _getNumCells(depth);}
    /**
     * @brief Obtain the number of active cells in the sparse grid at depth
     *  \f$t\f$.
     * @param depth The depth \f$t\f$.
     * @return The number of cells in the sparse grid at depth \f$t\f$.
     */
    inline IndexType getNumActiveCells(arma::uword const depth) const
    {return depth==0 ? sg.getNumActiveCells() : _getNumActiveCells(depth);}
    /**
     * @brief Obtain the number of partitions along the given axis of the sparse
     *  grid at depth \f$t\f$.
     * @param depth The depth \f$t\f$.
     * @param dim The dimension/axis whose number of partitions must be
     *  obtained.
     * @return The number of partitions along the given axis of the sparse grid
     *  at depth \f$t\f$.
     * @see HierarchicalSparseGrid::n
     */
    inline IndexType getNumAxisPartitions(
        arma::uword const depth, arma::uword const dim
    ) const{
        return depth==0 ?
            sg.getNumAxisPartitions(dim) :
            _getNumAxisPartitions(depth, dim)
        ;
    }
    /**
     * @brief Obtain the number of partitions for each axis at depth \f$t\f$.
     * @param depth The depth \f$t\f$.
     * @return The number of partitions for each axis of the sparse grid at
     *  depth \f$t\f$.
     */
    inline arma::Col<IndexType> const getNumAxisPartitions(
        arma::uword const depth
    ) const{
        return depth==0 ?
            sg.getNumAxisPartitions() :
            n.col(depth-1)
        ;
    }
    /**
     * @brief Obtain a reference to the map that encodes the active cells
     *  (typically for submanifold sparse convolutions) at depth \f$t\f$.
     * @param depth The depth \f$t\f$.
     * @return Reference to the map that encodes the active cells.
     */
    inline map<IndexType, IndexType> & getMap(
        arma::uword const depth
    ){
        return depth==0 ?
            sg.getMap() :
            _getMap(depth)
        ;
    }
    /**
     * @brief Obtain a reference to the downsampling map that links the active
     *  cell at depth \f$t+1\f$ with the cell at the min corner of the
     *  convolutional window sliding through the grid at depth \f$t\f$.
     * @param depth The depth \f$t\f$.
     * @return Reference to the downsampling map that links the active cell
     *  at depth \f$t+1\f$ with the min cell of the grid at depth \f$t\f$ for
     *  the corresponding downsampling convolution.
     * @see HierarchicalSparseGrid::hD
     */
    inline vector<IndexType> & getDownsamplingMap(arma::uword const depth)
    {return hD[depth];}
    /**
     * @brief Obtain a reference to the upsampling map that links the active
     *  cell at depth \f$t\f$ with the cell at the min corner of the
     *  convolutional window sliding through the grid at depth \f$t+1\f$.
     * @param depth The depth \f$t\f$.
     * @return Reference to the upsampling map that links the active cell at
     *  depth \f$t\f$ with the min cell of the grid at depth \f$t+1\f$ for
     *  the corresponding upsampling convolution.
     * @see HierarchicalSparseGrid::hU
     */
    inline vector<IndexType> & getUpsamplingMap(arma::uword const depth)
    {return hU[depth];}
    /**
     * @brief Obtain a const reference to the min vertex of the first sparse
     *  grid in the hierarchy.
     * @return Const reference to the min vertex of the first sparse grid.
     * @see SparseGrid::getMinVertex
     * @see SparseGrid::A
     */
    inline arma::Row<XDecimalType> getMinVertex() const
    {return sg.getMinVertex();}
    /**
     * @brief Check whether the execution time of the
     *  HierarchicalSparseGrid::fit method must be logged or not.
     * @return True if the execution time of HierarchicalSparseGrid::fit must
     *  be logged, false otherwise.
     * @see HierarchicalSparseGrid::logTime
     */
    inline bool getLogTime() const
    {return logTime;}
    /**
     * @brief Set whether the execution time of the
     *  HierarchicalSparseGrid::fit method must be logged or not.
     * @param logTime True to enable the logging of the execution time,
     *  false otherwise.
     * @see HierarchicalSparseGrid::logTime
     */
    inline void setLogTime(bool const logTime)
    {this->logTime = logTime;}

protected:
    /**
     * @brief Assists HierarchicalSparseGrid::getNumCells
     * @see HierarchicalSparseGrid::getNumCells
     */
    inline IndexType _getNumCells(arma::uword const depth) const
    {return arma::prod(n.col(depth-1));}
    /**
     * @brief Assists HierarchicalSparseGrid::getNumActiveCells
     * @see HierarchicalSparseGrid::getNumActiveCells
     */
    inline IndexType _getNumActiveCells(arma::uword const depth) const
    {return h[depth-1].size();}
    /**
     * @brief Assists HierarchicalSparseGrid::getNumAxisPartitions
     * @see HierarchicalSparseGrid::getNumAxisPartitions
     */
    inline IndexType _getNumAxisPartitions(
        arma::uword const depth,
        arma::uword const dim
    ) const
    {return n.col(depth-1)[dim];}
    /**
     * @brief Assists HierarchicalSparseGrid::getMap
     * @see HierarchicalSparseGrid::getMap
     */
    inline map<IndexType, IndexType> & _getMap(
        arma::uword const depth
    ){
        return h[depth-1];
    }
};

#include <adt/grid/HierarchicalSparseGrid.tpp>

}

#endif
